[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
FiniteHorizonGramians = "b59a298d-d283-4a37-9369-85a9f9a111a5"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
MatrixDepot = "b51810bb-c9f3-55da-ae3c-350fc1fbce05"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TuePlots = "7dc86ad5-723e-4492-bd0d-d0b58009a4c8"
